name: Genel Haber Botu
on:
  schedule:
    - cron: '0 * * * *'  # Her saatin başında çalışır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Kutuphaneleri Yukle
        run: pip install feedparser
      - name: Botu Calistir
        env:
          GMAIL_SIFRE: ${{ secrets.GMAIL_SIFRE }}
        run: python haberci.py
      - name: Hafizayi Guncelle
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add haber_hafiza.txt
          git commit -m "Haber hafizasi guncellendi" || exit 0
          git push
