name: Haber ve Oyun Botu
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  haber_gonder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Kutuphaneleri Yukle
        run: pip install feedparser google-generativeai
      - name: Botu Çalıştır
        env:
          GMAIL_SIFRE: ${{ secrets.GMAIL_SIFRE }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python haberci.py
      - name: Hafızayı Kaydet ve Pushla
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add haber_hafiza.txt
          git commit -m "Hafiza guncellendi [skip ci]" || echo "Degisiklik yok"
          git push
