name: Haber Botu Pro
on:
  schedule:
    - cron: '0 */2 * * *' # Her 2 saatte bir çalışır
  workflow_dispatch: # Manuel çalıştırma butonu
jobs:
  haber_paylas:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Kutuphaneleri Yukle
        run: pip install feedparser google-generativeai --upgrade
      - name: Botu Calistir
        env:
          GMAIL_SIFRE: ${{ secrets.GMAIL_SIFRE }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python haberci.py
      - name: Hafizayi Kaydet
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add haber_hafiza.txt
          git commit -m "Hafiza guncellendi [skip ci]" || echo "Degisiklik yok"
          git push
