name: Gunluk Haber Botu
on:
  schedule:
    - cron: '0 * * * *' # Her gün otomatik çalışır
  workflow_dispatch: # İstediğinde elle çalıştırmak için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        run: pip install feedparser

      - name: Botu Calistir
        env:
          GMAIL_SIFRE: ${{ secrets.GMAIL_SIFRE }} # Kasadaki şifreyi buraya bağladık
        run: python haberci.py
